### ISSUE TITLE
Text for Home, Search and  Your Library accented

### ISSUE THREAD

**Issue by o1x3** [material-ocean/Spotify-Theme#6] opened 2021-05-21 09:49 UTC
![image](https://user-images.githubusercontent.com/34067026/119118340-bd853480-ba47-11eb-9e26-f88c16815732.png)

It looks like this. Did I mess up any config?
Spicetify version 2.2.2
Spotify version 1.1.59.712.g54f36e5d-a
config.ini

```
[AdditionalOptions]
extensions  = keyboardShortcut.js|shuffle+.js|trashbin.js|webnowplaying.js
custom_apps = 

[Patch]

[Setting]
overwrite_assets        = 1
spotify_launch_flags    = 
check_spicetify_upgrade = 0
spotify_path            = D:\scoop\apps\spotify-latest\current
prefs_path              = C:\Users\<username>\AppData\Roaming\Spotify\prefs
inject_css              = 1
current_theme           = Material-Ocean
color_scheme            = Ocean
replace_colors          = 1

[Preprocesses]
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1
disable_sentry        = 1
disable_ui_logging    = 1

; DO NOT CHANGE!
[Backup]
version = 1.1.59.712.g54f36e5d

```

**Comment by Blacksuan19** [comment] 2021-05-21 12:27
Duplicate of #5

**Closed as completed** 2021-05-21 12:27 UTC
